# Generated by Django 2.2.11 on 2020-03-21 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='product',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
